### ISSUE TITLE
Support for Visual Studio 2017

### ISSUE THREAD

**Issue by theramis** [marazt/config-transformation#3] opened 2017-07-19 04:46 UTC
Hey, 

Would you have time to add support for Visual Studio 2017. 

Cheers.

**Comment by tbertenshaw** [comment] 2017-07-20 09:20
I've submitted a pr. (if you clone and build the vsix produced does work with vs2017) https://github.com/tbertenshaw/config-transformation

**Comment by marazt** [comment] 2017-07-20 17:04
Hi, sorry for the late answer. First, I'm glad you are using the extension. I have no time to migrate it yet, so thanks a lot for the PR. I will check it.

**Comment by marazt** [comment] 2017-07-20 17:48
@tbertenshaw, in which VS version did you build the solution? In VS2017, it could not reference EnvDTE, EnvDTE80, EnvDTE90 event they are referenced via Nuget. I have found similar issuer over the web. Maybe it can be caused by the fact that I have now installed VS2017 only. I will inspect it more deeply during the weekend. 

Thanks.

**Comment by tbertenshaw** [comment] 2017-07-20 20:03
i built it i think in 15.2 but on a machine with vs 2015 also. Come to think of it i think i had this issue and had to install some vs tools to resolve it. Just trying at home which has vs2017 only and having issues building/adding the nuget references to resolve. Will take a look when i get back to work with the machine which built it.

**Comment by marazt** [comment] 2017-07-20 20:50
Ok, so I will try to install VS2015 in VM and test it.

**Comment by tbertenshaw** [comment] 2017-07-21 07:50
Hi ok i think i see what the problem might be. because the gitignore didn't exclude the packages folder, some where checked in rather than being nuget references. I've just done the following.

- [x] added packages and .vs folders to the git ignore
- [x] deleted the packages folder from git.
- [x] added the vsixupdater package to the nuget references
- [x] moved the integration test project from within the configtransform project (not sure how it got inside there :)) 
- [x] updated the vstools version inside the csproj to 15.

**Comment by marazt** [comment] 2018-02-07 18:50
Fixed by #4 
New [version v1.4.0.0 released](https://marketplace.visualstudio.com/items?itemName=marazt.ConfigTransformation).

**Closed as completed by marazt** 2018-02-07 18:50 UTC
